openapi: 3.0.0
info:
  description: This is a simple API to get data about airports, airlines, and flights
  version: “1.0.0”
  title: AeroInfo.me API
servers:
  - url: 'http://aeroinfo.me/api'
  
paths:
  /airlines:
    get:
      summary: lists all current and upcoming flights.
      parameters:
        – in: query
        name: searchString
        description: gets flight data
        required: false
        schema:
          type: string
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter
  /airlines/airline_id:
    get:
      summary: lists all of the current active airlines.
      parameters:
        – in: query
        name: searchString
        description: gets airline data
        required: false
        schema:
          type: int
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter
  /airports:
    get:
      summary: lists all of the current active airlines.
      parameters:
        – in: query
        name: searchString
        description: gets airline data
        required: false
        schema:
          type: string
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter
  /airports/aiport_id:
    get:
      summary: airports sorted by their airport id.
      parameters:
        – in: query
        name: searchString
        description: gets airline data
        required: false
        schema:
          type: int
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter
  /flights:
    get:
      summary: retrieves information about all flights.
      parameters:
        – in: query
        name: searchString
        description: gets airport data
        required: false
        schema:
          type: string
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter
  /flights/flight_number:
    get:
      summary: filters flights by their flight number.
      parameters:
        – in: query
        name: searchString
        description: gets airport data
        required: false
        schema:
          type: int
      responses:
        ‘200’:
          description: search results matching criteria
        ‘400’:
          description: bad input parameter